### ISSUE TITLE
s

### ISSUE THREAD

**Issue by li-li123** [li-li123/li-li123.github.io#7]
s = 'A\oB\oC'
print(s)
print(len(s))
我这样输出的是7，但是预期应该是5，而且输出也不对，我的输出是A\oB\oC
预期应该是‘a\xooB\xooC'

**Comment by abadfox233** [comment]
\o  还是 \0

**Comment by li-li123** [comment]
我要下班啦，到家再向王老师请教呀😁

**Comment by li-li123** [comment]
你忙吗，我下了班跟你打电话，你那边方便不
